### ISSUE TITLE
Unecessary collection of data on official builds

### ISSUE THREAD

**Issue by kamikazechaser** [haxzie/instagram-live-streamer#29]
The official builds seem to be collecting the username of the logged in user. Your privacy policy does mention this. However I fail to understand why this is necessary. Sentry by default will only log unhandled exceptions. The methods implemented are logging to console by default (exceptions are handled). So in essence, this app seems to be collecting analytics on who installed and used the app (and how many times did that person login). Why not track downloads instead?

**Comment by haxzie** [comment]
Hey @kamikazechaser, thanks for raising this issue. We do collect the usernames of people who login to the app and it's at most very transparent on what details we collect. Instead of having a dedicated analytics server (Which we will be implementing in the future) it is essential for me to know the demographics of the users to further the developement of the application. If most of the users are from particular category it will help me to evaluate and prioritize certain features over others. And this is clearly mentioned in the privacy policy in very easy to understand way for anyone using the application. We have certain version of the app is dedicated to media agencies which uses multiple accounts, to collaborate with influeners. This is were the number of times logged in comes to picture, the app does a pretty good job of allowing the users to sign in only once and save their sessions, ie. It's only tracked once when the user logs in and only the subsequent logs under the user. This is how most of the analytics tool work with digital products but we are doing much less and things very transparently 🙌🏼 am happy to help with any further queries you might have and feel free to drop down your questions here so that it will be visible to others too.
